### ISSUE TITLE
Error in util/PaintingHandler.js:110

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#122] opened 2017-05-05 04:37 UTC
## Error in Place 2.0

**Error** in **util/PaintingHandler.js:110**
Batch is already running

[View on Bugsnag](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590c016fd8fcda0018de125e&i=gh&m=ci)

## Stacktrace

    util/PaintingHandler.js:110 - addPixel
    models/user.js:182 - none

[View full stacktrace](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590c016fd8fcda0018de125e&i=gh&m=ci)

**Comment by AppleBetas** [comment] 2017-05-05 04:38
Duplicate of #63

**Comment by nullpixel** [comment] 2017-05-07 20:13
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=590f7fcbcee08400187558a6&i=gh&m=ra)

**Comment by AppleBetas** [comment] 2017-05-07 20:13
Duplicate of #63

**Comment by nullpixel** [comment] 2017-05-08 20:14
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=5910d19e51897a0018a63eba&i=gh&m=ra)

**Comment by nullpixel** [comment] 2017-05-10 22:05
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=59138ea51d6f56001a99c60f&i=gh&m=ra)

**Comment by nullpixel** [comment] 2017-05-12 00:55
An error linked to this issue has been reopened in Bugsnag
[**Error** in **util/PaintingHandler.js:110**](https://app.bugsnag.com/dynastic-development/place-2-dot-0/errors/590c016fd8fcda0018de125f?event_id=591507c6092ddd0019338e3a&i=gh&m=ra)

**Comment by AppleBetas** [comment] 2017-05-17 01:59
Merged with #143 because line number changed and BugSnag is too stupid to realize that

**Closed as completed by AppleBetas** 2017-05-17 01:59 UTC
