### ISSUE TITLE
Sorting the date joined in ModTools is horribly inaccurate

### ISSUE THREAD

**Issue by EricRabil** [dynasticdevelop/place#86] opened 2017-04-29 06:17 UTC
When sorting ascending/descending the account created column in mod tools, the results do not correspond and are in a seemingly random order.

**Comment by AppleBetas** [comment] 2017-04-29 21:35
Not able to reproduce this

**Comment by EricRabil** [comment] 2017-04-29 21:35
Sec!

**Comment by AppleBetas** [comment] 2017-04-30 04:13
Turns out this bug does not actually exist, but is caused by the placement of the sorting indicator. It would be appreciated if you could open a separate issue or just PR fix for this

**Closed as completed by AppleBetas** 2017-04-30 04:13 UTC
Labels: bug
